'use server';

/**
 * @fileoverview This is the Genkit API route for Next.js.
 *
 * This file is automatically generated by the Genkit CLI.
 * It is not intended to be edited by hand.
 */

import {createNextApiHandler} from '@genkit-ai/next/server';
import '@/ai/flows/smart-tagging.ts';

const {GET, POST} = createNextApiHandler();
export {GET, POST};
