/**
 * @fileoverview This is the Genkit API route for Next.js.
 *
 * This file is automatically generated by the Genkit CLI.
 * It is not intended to be edited by hand.
 */

import createNextApiHandler from '@genkit-ai/next';
import { smartTagFlow } from '@/ai/flows/smart-tagging';

export const {GET, POST} = createNextApiHandler({
  flows: [smartTagFlow],
});
