// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A smart tagging AI agent for code snippets.
 *
 * - smartTag - A function that handles the code analysis and tag suggestion process.
 * - SmartTagInput - The input type for the smartTag function.
 * - SmartTagOutput - The return type for the smartTag function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SmartTagInputSchema = z.object({
  codeSnippet: z.string().describe('The code snippet to analyze.'),
});
export type SmartTagInput = z.infer<typeof SmartTagInputSchema>;

const SmartTagOutputSchema = z.object({
  tags: z.array(z.string()).describe('An array of suggested tags for the code snippet.'),
});
export type SmartTagOutput = z.infer<typeof SmartTagOutputSchema>;

export async function smartTag(input: SmartTagInput): Promise<SmartTagOutput> {
  return smartTagFlow(input);
}

const prompt = ai.definePrompt({
  name: 'smartTagPrompt',
  input: {schema: SmartTagInputSchema},
  output: {schema: SmartTagOutputSchema},
  prompt: `You are an AI expert in software development.

You will analyze the provided code snippet and suggest relevant tags that can be used to categorize and easily find the code snippet later.

Analyze the following code snippet and provide an array of relevant tags:

Code Snippet: {{{codeSnippet}}}

Tags:`,
});

const smartTagFlow = ai.defineFlow(
  {
    name: 'smartTagFlow',
    inputSchema: SmartTagInputSchema,
    outputSchema: SmartTagOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
