// This is an autogenerated file from Firebase Studio.
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  projectId: 'devflow-yuggg',
  appId: '1:299356954446:web:40446f60ef82ea9658081f',
  storageBucket: 'devflow-yuggg.firebasestorage.app',
  apiKey: 'AIzaSyB4VeWLofaEBblMTT_Pwguv2ORTkZzSdxs',
  authDomain: 'devflow-yuggg.firebaseapp.com',
  messagingSenderId: '299356954446',
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export {app, auth, db};